// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByZnUYoza6L6wJXkJ2Hz2OS-MG2dINnZY',
    appId: '1:669499884294:web:ef1eeeb245a81023711487',
    messagingSenderId: '669499884294',
    projectId: 'helloworld-8d689',
    authDomain: 'helloworld-8d689.firebaseapp.com',
    storageBucket: 'helloworld-8d689.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqPnel2FxcgDXhv6rkQ-t5WbQajrhx7_o',
    appId: '1:669499884294:android:a56c278b78286eab711487',
    messagingSenderId: '669499884294',
    projectId: 'helloworld-8d689',
    storageBucket: 'helloworld-8d689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAymF_-S1cpX35jCik3lKzo8DLsdQ96pOI',
    appId: '1:669499884294:ios:452a69dccb163a5f711487',
    messagingSenderId: '669499884294',
    projectId: 'helloworld-8d689',
    storageBucket: 'helloworld-8d689.appspot.com',
    iosBundleId: 'com.example.gdscApp',
  );
}
